#!/bin/bash
#Evan Meyerhoff
#Lab 1 Mid
#Printing n lines from file from a given start point.
shopt -s dotglob

#Grabbing n option
if [[ $1 =~ -n[1234567890] ]]; then
	noption=${1:2}
	shift
else
	noption=10
fi

#Grabbing starting line option
if [[ $1 =~ [0-9]{1,} ]]; then
	START_LINE=$1
	shift
else
	echo no start line arguement.	
fi


# Program main function
for file in "$@"; do
	if [[ -f "$file" ]]; then
		echo "########################################"
		echo File \"$file\" starting at $START_LINE with $noption lines.
		echo "########################################"
		cat "$file" | tail --lines=+$START_LINE | head -n $noption
	else 
		echo "$file" is not a filename.
	fi
	echo 
done

shopt -u dotglob
